## Soal 2 - Film Bagus 🎥

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
dfr = pd.read_csv('ratings.csv')
dfm = pd.read_csv('movies.csv')


In [3]:
dfr['userId'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

# Content Based Filtering

In [4]:
# dfm['genres'][1].split("|")

# 2. count vectorizer: hitung kata tiap data

cv = CountVectorizer()
cm = cv.fit_transform(dfm['genres'])

# total kata unik 
print(cv.get_feature_names())

# matrix freq tiap kata di tiap data
print(cm.toarray())
# print(cm.toarray()[0])

['action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'fi', 'film', 'genres', 'horror', 'imax', 'listed', 'musical', 'mystery', 'no', 'noir', 'romance', 'sci', 'thriller', 'war', 'western']
[[0 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
# 3. Cosine similarity dari tiap data di matrix freq

cosScore = cosine_similarity(cm.toarray())
cosScore

array([[1.        , 0.77459667, 0.31622777, ..., 0.4472136 , 0.        ,
        0.        ],
       [0.77459667, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.31622777, 0.        , 1.        , ..., 0.70710678, 0.        ,
        0.        ],
       ...,
       [0.4472136 , 0.        , 0.70710678, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [6]:
# 4. Gunakan cos score sbg data rekomendasi
sayaSuka = dfm[dfm['title'] == 'Superman vs. The Elite (2012)'].index.values[0]

# daftar seluruh Movie beserta cos score
similarMovie = list(enumerate(cosScore[sayaSuka]))
# similarCars  # (index, %similarity)

In [7]:
# sort berdasarkan %similarity
similarMovie = sorted(similarMovie, key=lambda x: x[1], reverse=True)
# similarCars

In [8]:
# 5 Movie yang mirip


dfSim = []
for i in similarMovie[:5]:
    dfSim.append(dfm.iloc[i[0]])
dfSim = pd.DataFrame(dfSim)
dfSim

movieId                                              title  \
6260     26913  Street Fighter II: The Animated Movie (Sutorît...   
8637     79274                  Batman: Under the Red Hood (2010)   
9370     94974                      Superman vs. The Elite (2012)   
9570     99813     Batman: The Dark Knight Returns, Part 2 (2013)   
10167   124867          Justice League: Throne of Atlantis (2015)   

                 genres  
6260   Action|Animation  
8637   Action|Animation  
9370   Action|Animation  
9570   Action|Animation  
10167  Action|Animation

# Collaborative Filtering

In [9]:
movwidodo = dfm[dfm['title'] == 'Being Flynn (2012)']['movieId']
idwidodo = movwidodo.values[0]
idwidodo

95816

In [10]:
dfrn = dfr.copy()
dfrn.drop(columns=['timestamp'])

userId  movieId  rating
0            1       16     4.0
1            1       24     1.5
2            1       32     4.0
3            1       47     4.0
4            1       50     4.0
...        ...      ...     ...
105334     668   142488     4.0
105335     668   142507     3.5
105336     668   143385     4.0
105337     668   144976     2.5
105338     668   148626     4.5

[105339 rows x 3 columns]

In [11]:
dfrn = dfr.pivot_table(columns=['movieId'],index=['userId'],values=['rating'])
dfrn = dfrn.fillna(0)
dfrn

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2          5.0    0.0    2.0    0.0    3.0    0.0    0.0    0.0    0.0    0.0   
3          0.0    0.0    0.0    0.0    3.0    0.0    3.0    0.0    0.0    0.0   
4          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5          4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
664        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
665        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
666        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
667        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
668        3.0    3.0    2.0    0.0    2.5    5.0    3.0    0.0    0.0    3.5   

         ...                                                                 \
movieId  ... 144482 144656 144976 146344 146656 146684 146878 148238 148626   
userId   ...                                                                  
1        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
664      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
665      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
666      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
667      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
668      ...    0.0    0.0    2.5    0.0    0.0    0.0    0.0    0.0    4.5   

                
movieId 149532  
userId          
1          0.0  
2          0.0  
3          0.0  
4          0.0  
5          0.0  
...        ...  
664        0.0  
665        0.0  
666        0.0  
667        0.0  
668        0.0  

[668 rows x 10325 columns]

In [12]:
dfcor = dfrn.corr().loc['rating']
dfcor = dfcor.fillna(0)
dfcor.head(10)

rating                                                              \
movieId    1         2         3         4         5         6         7        
movieId                                                                         
1        1.000000  0.229124  0.222062  0.079319  0.243736  0.211601  0.237869   
2        0.229124  1.000000  0.108133  0.085610  0.123400  0.182489  0.111970   
3        0.222062  0.108133  1.000000  0.145779  0.469828  0.224401  0.281310   
4        0.079319  0.085610  0.145779  1.000000  0.095993  0.136973  0.067767   
5        0.243736  0.123400  0.469828  0.095993  1.000000  0.123640  0.366064   
6        0.211601  0.182489  0.224401  0.136973  0.123640  1.000000  0.226081   
7        0.237869  0.111970  0.281310  0.067767  0.366064  0.226081  1.000000   
8        0.066370  0.035200  0.161308  0.184446  0.177667  0.004951 -0.019352   
9        0.026712  0.043333  0.188836  0.006738  0.086260  0.279029  0.182871   
10       0.156136  0.314376  0.039788  0.127035  0.052069  0.265137  0.115573   

                                       ...                                \
movieId    8         9         10      ...    144482    144656    144976   
movieId                                ...                                 
1        0.066370  0.026712  0.156136  ...  0.053224 -0.027328  0.054386   
2        0.035200  0.043333  0.314376  ...  0.082551  0.082551  0.035785   
3        0.161308  0.188836  0.039788  ... -0.011447 -0.011447  0.032102   
4        0.184446  0.006738  0.127035  ... -0.004763 -0.004763 -0.006649   
5        0.177667  0.086260  0.052069  ... -0.011947 -0.011947  0.040914   
6        0.004951  0.279029  0.265137  ...  0.068936  0.105883  0.147809   
7       -0.019352  0.182871  0.115573  ... -0.011248  0.130140  0.186369   
8        1.000000 -0.011925  0.069449  ... -0.002579 -0.002579 -0.003601   
9       -0.011925  1.000000  0.096960  ... -0.006932 -0.006932  0.047453   
10       0.069449  0.096960  1.000000  ...  0.072429  0.098554  0.090472   

                                                                               
movieId    146344    146656    146684    146878    148238    148626    149532  
movieId                                                                        
1       -0.027328  0.026201 -0.027328 -0.027328 -0.027328  0.026451 -0.027328  
2        0.082551  0.115655 -0.015020 -0.015020  0.082551  0.081235  0.082551  
3       -0.011447 -0.016037 -0.011447 -0.011447 -0.011447  0.029735 -0.011447  
4       -0.004763 -0.006673 -0.004763 -0.004763 -0.004763 -0.008250 -0.004763  
5       -0.011947 -0.016738 -0.011947 -0.011947 -0.011947  0.038672 -0.011947  
6        0.105883  0.118764 -0.017275 -0.017275  0.105883  0.109557  0.105883  
7        0.130140  0.069135 -0.011248 -0.011248  0.130140  0.139296  0.130140  
8       -0.002579 -0.003614 -0.002579 -0.002579 -0.002579 -0.004468 -0.002579  
9       -0.006932 -0.009711 -0.006932 -0.006932 -0.006932  0.151573 -0.006932  
10       0.098554  0.117160 -0.019007 -0.019007  0.098554  0.134155  0.098554  

[10 rows x 10325 columns]

In [14]:
dfr[dfr['movieId'] == idwidodo]

userId  movieId  rating   timestamp
104869     668    95816     2.5  1351303077

In [15]:
ratingwidodo = 5

In [22]:
skor = dfcor['rating'][movwidodo.values[0]] * ratingwidodo
skor = skor.sort_values(ascending=False)
print(skor.index[:5])


Int64Index([7086, 4801, 6898, 87660, 53038], dtype='int64', name='movieId')


In [25]:

filmwidodo = []
for i in finaldf:
    filmwidodo.append(dfm[dfm['movieId'] == i].index[0])

filmwidodo

[5162, 3755, 5020, 9033, 7381]

## Rekomendasi Widodo

In [26]:
RekomWidodo = pd.DataFrame(dfm.iloc[filmwidodo])
RekomWidodo

movieId                     title        genres
5162     7086          Pygmalion (1938)  Comedy|Drama
3755     4801  Little Foxes, The (1941)         Drama
5020     6898      Sweet Sixteen (2002)         Drama
9033    87660    Too Big to Fail (2011)         Drama
7381    53038           Red Dust (1932)         Drama